/* Road of the Horde — procedural 3D prototype, no image assets required. */
(()=>{
'use strict';
const $=id=>document.getElementById(id);
const canvas=$('scene');
let scene,camera,renderer,clock;
let gameState='menu',paused=false,wave=1,armyCount=8,boss=null,bossHp=1000,bossMax=1000;
let playerX=0,targetX=0,worldSpeed=7,runDistance=0,gateTimer=2.5,enemyTimer=0,shootTimer=0,spawnTimer=0,bonusAvailable=false;
let combo=0,comboTimer=0,maxCombo=0,score=0,coins=0,shieldActive=false,shieldTimer=0,slowMoActive=false,slowMoTimer=0;
let rapidFireActive=false,rapidFireTimer=0,magnetActive=false,magnetTimer=0,freezeActive=false,freezeTimer=0;
let difficultyMultiplier=1,enemiesKilled=0,totalKills=0;
const soldiers=[], enemies=[], bullets=[], particles=[], gates=[], props=[], coinObjects=[], shockwaves=[];
let touchActive=false,lastTouchX=0;
let audioCtx=null,masterGain=null,musicGain=null,sfxGain=null,musicTimer=null,musicStep=0,audioMuted=false;
const mats={};

function init(){
  scene=new THREE.Scene(); scene.background=new THREE.Color(0xf2c878); scene.fog=new THREE.Fog(0xf2c878,35,115);
  camera=new THREE.PerspectiveCamera(52,innerWidth/innerHeight,.1,220); camera.position.set(0,8.8,13.5); camera.lookAt(0,2,-8);
  renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'}); renderer.setPixelRatio(Math.min(devicePixelRatio,1.7)); renderer.setSize(innerWidth,innerHeight); renderer.shadowMap.enabled=true; renderer.shadowMap.type=THREE.PCFSoftShadowMap; renderer.outputColorSpace=THREE.SRGBColorSpace; renderer.toneMapping=THREE.ACESFilmicToneMapping; renderer.toneMappingExposure=1.05;
  clock=new THREE.Clock();
  const hemi=new THREE.HemisphereLight(0xffe9bf,0x604a2c,2.0); scene.add(hemi);
  const sun=new THREE.DirectionalLight(0xffe6b0,3.2); sun.position.set(-12,25,10); sun.castShadow=true; sun.shadow.mapSize.set(1024,1024); sun.shadow.camera.left=-25;sun.shadow.camera.right=25;sun.shadow.camera.top=35;sun.shadow.camera.bottom=-20; scene.add(sun);
  buildMaterials(); buildWorld(); buildHorde(); setupInput(); setupUI(); window.addEventListener('resize',resize); window.addEventListener('external-pause',()=>setPause(true,'external')); window.addEventListener('external-resume',()=>{if(gameState==='play'&&paused)setPause(false,'external')});
  window.addEventListener('yandex-ready',()=>{});
  animate();
}
function buildMaterials(){
  mats.road=new THREE.MeshStandardMaterial({color:0x34383b,roughness:.95}); mats.line=new THREE.MeshBasicMaterial({color:0xf5eee0}); mats.sand=new THREE.MeshStandardMaterial({color:0xd8a65d,roughness:1}); mats.sand2=new THREE.MeshStandardMaterial({color:0xe8bf78,roughness:1}); mats.green=new THREE.MeshStandardMaterial({color:0x3d7d37}); mats.cactus=new THREE.MeshStandardMaterial({color:0x4f8b41}); mats.wood=new THREE.MeshStandardMaterial({color:0x9b5d27,roughness:.85}); mats.gold=new THREE.MeshStandardMaterial({color:0xffbd37,metalness:.25,roughness:.45}); mats.red=new THREE.MeshStandardMaterial({color:0xb92824,roughness:.6}); mats.zombie=new THREE.MeshStandardMaterial({color:0x6e7f59,roughness:.9}); mats.skin=new THREE.MeshStandardMaterial({color:0xb77b58}); mats.uniform=new THREE.MeshStandardMaterial({color:0x30353a,roughness:.85}); mats.weapon=new THREE.MeshStandardMaterial({color:0x8b9397,metalness:.8,roughness:.3}); mats.black=new THREE.MeshStandardMaterial({color:0x141719,roughness:.75}); mats.white=new THREE.MeshStandardMaterial({color:0xd9dde0});
  mats.shield=new THREE.MeshStandardMaterial({color:0x4dc9ff,metalness:.6,roughness:.3,transparent:true,opacity:.7}); mats.coin=new THREE.MeshStandardMaterial({color:0xffd700,metalness:.8,roughness:.2}); mats.powerup=new THREE.MeshStandardMaterial({color:0x9b4dff,metalness:.4,roughness:.4});
  mats.rapidfire=new THREE.MeshStandardMaterial({color:0xff4d4d,metalness:.5,roughness:.3}); mats.magnet=new THREE.MeshStandardMaterial({color:0xff00ff,metalness:.6,roughness:.3}); mats.freeze=new THREE.MeshStandardMaterial({color:0x00ffff,metalness:.5,roughness:.3});
}
function box(w,h,d,mat){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat);m.castShadow=true;m.receiveShadow=true;return m}
function cyl(r1,r2,h,mat,seg=10){const m=new THREE.Mesh(new THREE.CylinderGeometry(r1,r2,h,seg),mat);m.castShadow=true;m.receiveShadow=true;return m}
function buildWorld(){
  const road=box(12,.25,190,mats.road); road.position.set(0,-.18,-55); scene.add(road);
  const left=box(20,.18,190,mats.sand);left.position.set(-16,-.25,-55);scene.add(left); const right=left.clone();right.position.x=16;scene.add(right);
  for(let z=7;z>-110;z-=6){let l=box(.12,.03,2.2,mats.line);l.position.set(0,.01,z);scene.add(l)}
  const edgeL=box(.16,.05,190,mats.line);edgeL.position.set(-5.85,.03,-55);scene.add(edgeL);const edgeR=edgeL.clone();edgeR.position.x=5.85;scene.add(edgeR);
  for(let i=0;i<34;i++){const z=5-i*3.5;spawnCactus(-7-Math.random()*8,z);spawnCactus(7+Math.random()*8,z-.8)}
  for(let i=0;i<16;i++){const z=-8-i*6;spawnCar((Math.random()<.5?-1:1)*(9+Math.random()*5),z)}
}
function spawnCactus(x,z){const g=new THREE.Group();const trunk=cyl(.28,.34,2.1,mats.cactus,8);trunk.position.y=1.05;g.add(trunk);for(const s of [-1,1]){const arm=cyl(.16,.2,.9,mats.cactus,8);arm.position.set(s*.38,1.25,0);arm.rotation.z=s*1.05;g.add(arm)}g.position.set(x,0,z);scene.add(g);props.push(g)}
function spawnCar(x,z){const g=new THREE.Group();const body=box(2.4,.55,4,mats.black);body.position.set(0,.45,0);g.add(body);for(const xx of [-.8,.8])for(const zz of [-1.2,1.2]){const w=cyl(.28,.28,.18,mats.black,12);w.rotation.z=Math.PI/2;w.position.set(xx,.25,zz);g.add(w)}g.position.set(x,0,z);g.rotation.y=Math.random()*Math.PI;scene.add(g);props.push(g)}
function soldierModel(color=0x30353a,scale=1){
  const g=new THREE.Group();g.scale.setScalar(scale);
  const body=box(.46,.75,.28,new THREE.MeshStandardMaterial({color,roughness:.9}));body.position.y=1.05;g.add(body);
  const head=cyl(.19,.2,.28,mats.skin,12);head.position.y=1.62;g.add(head);
  const helmet=cyl(.24,.25,.12,mats.black,12);helmet.position.y=1.79;g.add(helmet);
  const leg1=box(.15,.62,.17,mats.uniform);leg1.position.set(-.12,.45,0);g.add(leg1);const leg2=leg1.clone();leg2.position.x=.12;g.add(leg2);
  const arm1=box(.13,.55,.14,mats.uniform);arm1.position.set(-.35,1.08,0);arm1.rotation.z=-.15;g.add(arm1);const arm2=arm1.clone();arm2.position.x=.35;arm2.rotation.z=.15;g.add(arm2);
  const gun=box(.1,.12,.72,mats.weapon);gun.position.set(0,1.1,-.43);g.add(gun);const muzzle=box(.12,.12,.15,mats.black);muzzle.position.set(0,1.1,-.84);g.add(muzzle);
  g.userData={phase:Math.random()*Math.PI*2, gun}; return g;
}
function buildHorde(){for(let i=0;i<armyCount;i++)addSoldier(i)}
function addSoldier(i){const s=soldierModel(0x30363b, .92+Math.random()*.1);s.position.set((i%5-2)*.62,0,3+Math.floor(i/5)*.72);scene.add(s);soldiers.push(s)}
function removeSoldier(){const s=soldiers.pop();if(s){scene.remove(s)}}
function setArmy(n){n=Math.max(0,Math.min(120,Math.floor(n)));while(soldiers.length<n)addSoldier(soldiers.length);while(soldiers.length>n)removeSoldier();armyCount=n;$('armyCount').textContent=n;if(n<=0)gameOver()}
function formationUpdate(t){const cols=Math.min(9,Math.max(3,Math.ceil(Math.sqrt(soldiers.length))));soldiers.forEach((s,i)=>{const row=Math.floor(i/cols),col=i%cols;const center=(Math.min(cols,soldiers.length-row*cols)-1)/2;s.userData.baseX=(col-center)*.63;s.userData.baseZ=3+row*.72;s.position.x+=(playerX+s.userData.baseX-s.position.x)*Math.min(1,t*8);s.position.z+=(s.userData.baseZ-s.position.z)*Math.min(1,t*8);s.position.y=Math.abs(Math.sin(performance.now()*.008+s.userData.phase))*.045;s.rotation.y=Math.sin(performance.now()*.004+s.userData.phase)*.05})}
function createGate(x,op,value){const g=new THREE.Group();const postMat=new THREE.MeshStandardMaterial({color:op==='+'?0x45bce8:0xe84c45,metalness:.1,roughness:.6});for(const px of [-1.75,1.75]){const p=box(.18,2.7,.28,postMat);p.position.set(px,1.35,0);g.add(p)}const top=box(3.7,.18,.3,postMat);top.position.y=2.65;g.add(top);const panel=box(3.1,1.2,.16,op==='+'?new THREE.MeshStandardMaterial({color:0x1b9bd0,transparent:true,opacity:.86}):new THREE.MeshStandardMaterial({color:0xcf302b,transparent:true,opacity:.86}));panel.position.set(0,1.35,0);g.add(panel);const c=document.createElement('canvas');c.width=256;c.height=128;const ctx=c.getContext('2d');ctx.fillStyle='white';ctx.font='bold 70px Arial';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(op+value,128,68);const tex=new THREE.CanvasTexture(c);const label=new THREE.Mesh(new THREE.PlaneGeometry(2.7,1.35),new THREE.MeshBasicMaterial({map:tex,transparent:true}));label.position.set(0,1.35,-.1);g.add(label);g.position.set(x,0,-28-Math.random()*10);g.userData={op,value,passed:false};scene.add(g);gates.push(g)}
function spawnGatePair(){const vals=[['+',2],['+',3],['+',5],['x',2],['-',2],['S',0],['⏱',0],['R',0],['M',0],['F',0]];let a=vals[Math.floor(Math.random()*vals.length)],b=vals[Math.floor(Math.random()*vals.length)];if(a[0]==='-'&&b[0]==='-')b=['+',3];createGate(-2,a[0],a[1]);createGate(2,b[0],b[1])}
function applyGate(g){if(g.userData.passed)return;g.userData.passed=true;const {op,value}=g.userData;if(op==='+')setArmy(armyCount+value);else if(op==='-')setArmy(armyCount-value);else if(op==='x')setArmy(Math.min(120,armyCount*value));else if(op==='S'){shieldActive=true;shieldTimer=8;sfx('bonus');burst(g.position,0x4dc9ff,20)}else if(op==='⏱'){slowMoActive=true;slowMoTimer=6;worldSpeed*=0.5;sfx('bonus');burst(g.position,0x9b4dff,20)}else if(op==='R'){rapidFireActive=true;rapidFireTimer=8;sfx('bonus');burst(g.position,0xff4d4d,20)}else if(op==='M'){magnetActive=true;magnetTimer=10;sfx('bonus');burst(g.position,0xff00ff,20)}else if(op==='F'){freezeActive=true;freezeTimer=5;sfx('bonus');burst(g.position,0x00ffff,20)}else setArmy(Math.min(120,armyCount*value));burst(g.position,op==='-'?0xe83d32:0x4dc9ff,16);sfx('gate')}
function enemyModel(bossType=false){const g=new THREE.Group();const scale=bossType?2.5:1;g.scale.setScalar(scale);const body=box(.75,.95,.5,bossType?new THREE.MeshStandardMaterial({color:0xc94038}):mats.zombie);body.position.y=1.1;g.add(body);const head=cyl(.31,.34,.5,bossType?mats.skin:mats.zombie,12);head.position.y=1.9;g.add(head);const eye=box(.07,.07,.05,mats.red);eye.position.set(-.12,1.95,-.29);g.add(eye);const eye2=eye.clone();eye2.position.x=.12;g.add(eye2);for(const x of [-.45,.45]){const arm=box(.18,.8,.2,bossType?mats.skin:mats.zombie);arm.position.set(x,1.15,0);arm.rotation.z=x*.18;g.add(arm)}for(const x of [-.2,.2]){const leg=box(.2,.8,.22,bossType?mats.skin:mats.zombie);leg.position.set(x,.4,0);g.add(leg)}return g}
function spawnEnemy(){const e=enemyModel(false);e.position.set((Math.random()*2-1)*4.2,0,-26-Math.random()*8);e.userData={hp:45,speed:Math.random()*.6+1.3};scene.add(e);enemies.push(e)}
function spawnBoss(){if(boss)return;boss=enemyModel(true);boss.position.set(0,0,-38);scene.add(boss);bossHp=bossMax=1000; $('bossWrap').classList.remove('hidden');$('bossHpText').textContent=bossHp;$('bossHpBar').style.width='100%';sfx('boss')}
function damageBoss(amount){if(!boss)return;bossHp=Math.max(0,bossHp-amount);$('bossHpText').textContent=Math.ceil(bossHp);$('bossHpBar').style.width=(bossHp/bossMax*100)+'%';boss.position.x+=(Math.random()-.5)*.08;burst(boss.position,0xff9a56,3);if(bossHp<=0){scene.remove(boss);boss=null;$('bossWrap').classList.add('hidden');wave++;$('waveText').textContent=wave;setArmy(armyCount+5);bonusAvailable=true;$('adButtonWrap').classList.remove('hidden');setTimeout(()=>{if(gameState==='play')nextWave()},900)}}
function shoot(){if(gameState!=='play'||paused||armyCount<=0)return;const count=Math.min(4,Math.max(1,Math.floor(armyCount/15)+1))*(rapidFireActive?2:1);for(let i=0;i<count;i++){const b=new THREE.Mesh(new THREE.SphereGeometry(.055,6,6),new THREE.MeshBasicMaterial({color:shieldActive?0x4dc9ff:(rapidFireActive?0xff4d4d:0xffd56a)}));b.position.set(playerX+(Math.random()-.5)*2.2,1.1,-1.5-Math.random()*1.5);b.userData={vx:(Math.random()-.5)*.6,vz:-30*(rapidFireActive?1.5:1),life:2};scene.add(b);bullets.push(b)}sfx('shot')}
function updateBullets(dt){for(let i=bullets.length-1;i>=0;i--){const b=bullets[i];b.position.z+=b.userData.vz*dt;b.position.x+=b.userData.vx*dt;b.userData.life-=dt;let hit=false;if(boss&&b.position.distanceTo(boss.position)<2.2){damageBoss(shieldActive?10+Math.random()*8:5+Math.random()*5);hit=true}for(let j=enemies.length-1;j>=0&&!hit;j--){const e=enemies[j];if(b.position.distanceTo(e.position)<1){e.userData.hp-=shieldActive?40:20;hit=true;if(e.userData.hp<=0){combo++;comboTimer=2.5;score+=10+combo*2;burst(e.position,0xb8d37a,9);scene.remove(e);enemies.splice(j,1);setArmy(armyCount+1);sfx('kill')}}}if(hit||b.userData.life<=0){scene.remove(b);bullets.splice(i,1)}}}
function updateEnemies(dt){for(let i=enemies.length-1;i>=0;i--){const e=enemies[i];e.position.z+=e.userData.speed*dt*2.4;e.position.x+=(playerX-e.position.x)*dt*.45;if(e.position.z>2){scene.remove(e);enemies.splice(i,1);if(shieldActive){combo++;score+=5}else{setArmy(armyCount-1);combo=0}burst(new THREE.Vector3(playerX,1,1),0xff4b3e,5)}}if(boss){boss.position.z+=dt*(slowMoActive?0.5:1.1);if(boss.position.z>2){if(shieldActive){damageBoss(50);boss.position.z=-2}else{setArmy(armyCount-Math.ceil(dt*4));boss.position.z=-2}}}}
function updateGates(dt){for(let i=gates.length-1;i>=0;i--){const g=gates[i];g.position.z+=worldSpeed*dt;if(g.position.z>4){scene.remove(g);gates.splice(i,1);continue}if(!g.userData.passed&&g.position.z>2.4&&g.position.z<3.4&&Math.abs(g.position.x-playerX)<1.9)applyGate(g)}}
function updateWorld(dt){if(slowMoActive){slowMoTimer-=dt;if(slowMoTimer<=0){slowMoActive=false;worldSpeed=7}}if(shieldActive){shieldTimer-=dt;if(shieldTimer<=0)shieldActive=false}if(rapidFireActive){rapidFireTimer-=dt;if(rapidFireTimer<=0)rapidFireActive=false}if(magnetActive){magnetTimer-=dt;if(magnetTimer<=0)magnetActive=false}if(freezeActive){freezeTimer-=dt;if(freezeTimer<=0)freezeActive=false}if(comboTimer>0){comboTimer-=dt;if(comboTimer<=0){if(combo>maxCombo)maxCombo=combo;combo=0}}runDistance+=worldSpeed*dt;gateTimer-=dt;enemyTimer-=dt;shootTimer-=dt;if(gateTimer<=0){spawnGatePair();gateTimer=4.2+Math.random()*1.8}if(wave>=2&&enemyTimer<=0&&!freezeActive){spawnEnemy();enemyTimer=.9-Math.min(.35,wave*.03)}if(runDistance>35&&!boss&&wave%2===0)spawnBoss();if(shootTimer<=0){shootTimer=rapidFireActive?.16:.32;shoot()}props.forEach(p=>{p.position.z+=worldSpeed*dt*.35;if(p.position.z>12)p.position.z-=120});updatePowerups(dt)}
function burst(pos,color,n){for(let i=0;i<n;i++){const p=new THREE.Mesh(new THREE.SphereGeometry(.035+Math.random()*.05,5,5),new THREE.MeshBasicMaterial({color,transparent:true}));p.position.copy(pos);p.userData={vx:(Math.random()-.5)*5,vy:Math.random()*5,vz:(Math.random()-.5)*5,life:.4+Math.random()*.6};scene.add(p);particles.push(p)}}
function updateParticles(dt){for(let i=particles.length-1;i>=0;i--){const p=particles[i];p.userData.life-=dt;p.position.x+=p.userData.vx*dt;p.position.y+=p.userData.vy*dt;p.position.z+=p.userData.vz*dt;p.userData.vy-=8*dt;p.scale.multiplyScalar(.96);if(p.userData.life<=0){scene.remove(p);particles.splice(i,1)}}}
function nextWave(){runDistance=0;gateTimer=1;enemyTimer=.3; $('waveText').textContent=wave; if(wave%2===0)spawnBoss()}
function startGame(){gameState='play';paused=false;wave=1;runDistance=0;armyCount=8;targetX=playerX=0;bonusAvailable=false;combo=0;maxCombo=0;score=0;coins=0;shieldActive=false;slowMoActive=false;rapidFireActive=false;magnetActive=false;freezeActive=false;$('menu').classList.add('hidden');$('pauseOverlay').classList.add('hidden');$('gameoverOverlay').classList.add('hidden');$('adButtonWrap').classList.add('hidden');$('hud').classList.remove('hidden');$('bossWrap').classList.add('hidden');$('waveText').textContent=wave;clearDynamic();setArmy(armyCount);startAudio();YandexBridge.start();sfx('start')}
function clearDynamic(){[...enemies,...bullets,...gates,...particles,...coinObjects].forEach(o=>scene.remove(o));enemies.length=bullets.length=gates.length=particles.length=coinObjects.length=0;if(boss){scene.remove(boss);boss=null}}
function gameOver(){if(gameState==='over')return;gameState='over';paused=false;YandexBridge.stop();stopAudio();$('hud').classList.add('hidden');$('gameoverOverlay').classList.remove('hidden');$('resultWave').textContent=wave;$('resultArmy').textContent=armyCount;sfx('fail')}
function setPause(v,reason='manual'){if(gameState!=='play')return;paused=v;$('pauseOverlay').classList.toggle('hidden',!v);if(v){YandexBridge.stop();muteAudio(true)}else{YandexBridge.start();muteAudio(false)}if(reason==='external'&&!v){} }
function setupUI(){const bind=(id,fn)=>{const el=$(id); if(!el)return; el.addEventListener('click',fn); el.addEventListener('pointerup',(e)=>{if(e.pointerType!=='mouse')fn(e)});};bind('playBtn',startGame);$('restartBtn').onclick=startGame;$('resumeBtn').onclick=()=>setPause(false);$('pauseRestart').onclick=startGame;$('pauseBtn').onclick=()=>setPause(!paused);$('adBtn').onclick=async()=>{if(!bonusAvailable)return;bonusAvailable=false;$('adButtonWrap').classList.add('hidden');await YandexBridge.fullscreen();if(gameState==='play'){setArmy(armyCount*2);sfx('bonus')}};YandexBridge.on('open',()=>{if(gameState==='play')setPause(true,'ad')});YandexBridge.on('close',()=>{if(gameState==='play')setPause(false,'ad')});YandexBridge.on('error',()=>{if(gameState==='play')setPause(false,'ad')});updateHUD()}
function setupInput(){const down=e=>{touchActive=true;lastTouchX=(e.touches?e.touches[0].clientX:e.clientX)};const move=e=>{if(!touchActive||gameState!=='play'||paused)return;const x=e.touches?e.touches[0].clientX:e.clientX;const dx=(x-lastTouchX)/Math.max(1,innerWidth);targetX=THREE.MathUtils.clamp(targetX+dx*9,-4.4,4.4);lastTouchX=x};const up=()=>touchActive=false;canvas.addEventListener('pointerdown',down);canvas.addEventListener('pointermove',move);window.addEventListener('pointerup',up);canvas.addEventListener('touchstart',down,{passive:true});canvas.addEventListener('touchmove',move,{passive:true});window.addEventListener('touchend',up)}
function resize(){camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,1.7))}
function updateCamera(dt){playerX+=(targetX-playerX)*Math.min(1,dt*8);camera.position.x+=(playerX*.42-camera.position.x)*Math.min(1,dt*4);camera.position.y=8.7+Math.sin(performance.now()*.002)*.05;camera.lookAt(playerX*.25,1.7,-9)}
function startAudio(){if(audioCtx)return;try{audioCtx=new (window.AudioContext||window.webkitAudioContext)();masterGain=audioCtx.createGain();musicGain=audioCtx.createGain();sfxGain=audioCtx.createGain();masterGain.gain.value=.65;musicGain.gain.value=.08;sfxGain.gain.value=.18;musicGain.connect(masterGain);sfxGain.connect(masterGain);masterGain.connect(audioCtx.destination);musicTimer=setInterval(musicTick,260)}catch(e){}}
function muteAudio(v){audioMuted=v;if(masterGain)masterGain.gain.setTargetAtTime(v?0:.65,audioCtx.currentTime,.03)}
function stopAudio(){muteAudio(true);}
function tone(freq,dur,type='square',gain=.1){if(!audioCtx||audioMuted)return;const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(0,audioCtx.currentTime);g.gain.linearRampToValueAtTime(gain,audioCtx.currentTime+.008);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+dur);o.connect(g);g.connect(sfxGain);o.start();o.stop(audioCtx.currentTime+dur+.02)}
function sfx(type){if(!audioCtx)return;const map={shot:[105,.055,'square',.045],kill:[180,.1,'sawtooth',.07],gate:[520,.16,'triangle',.09],boss:[70,.5,'sawtooth',.11],start:[240,.2,'triangle',.08],fail:[80,.5,'sawtooth',.1],bonus:[660,.25,'triangle',.1]};const a=map[type];if(a)tone(...a)}
function musicTick(){if(!audioCtx||audioMuted||gameState!=='play'||paused)return;const scale=[110,130.81,146.83,164.81,196,220,246.94,293.66];const f=scale[musicStep%scale.length]*(musicStep%16===12?2:1);toneMusic(f,.18);if(musicStep%4===0)toneMusic(f/2,.24);musicStep++}
function toneMusic(freq,dur){const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type='triangle';o.frequency.value=freq;g.gain.value=.06;g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+dur);o.connect(g);g.connect(musicGain);o.start();o.stop(audioCtx.currentTime+dur+.02)}
function animate(){requestAnimationFrame(animate);const dt=Math.min(.033,clock.getDelta());if(gameState==='play'&&!paused){updateWorld(dt);formationUpdate(dt);updateGates(dt);updateEnemies(dt);updateBullets(dt);updateParticles(dt);updateCamera(dt);updateHUD()}else{updateParticles(dt);updateCamera(dt)}renderer.render(scene,camera)}

// Power-up spawn and collection system
function updatePowerups(dt){if(Math.random()<0.02&&coinObjects.length<3){spawnCoin()}for(let i=coinObjects.length-1;i>=0;i--){const c=coinObjects[i];c.position.z+=worldSpeed*dt;c.rotation.y+=dt*3;let dist=c.position.distanceTo(new THREE.Vector3(playerX,0.5,0));if(magnetActive&&dist<8){c.position.x+=(playerX-c.position.x)*dt*4;c.position.z+=(0-c.position.z)*dt*4}if(c.position.z>8){scene.remove(c);coinObjects.splice(i,1);continue}if(dist<1.2){coins++;score+=50;burst(c.position,0xffd700,8);scene.remove(c);coinObjects.splice(i,1);sfx('bonus')}}}
function spawnCoin(){const c=new THREE.Mesh(new THREE.CylinderGeometry(0.3,0.3,0.05,16),mats.coin);c.rotation.x=Math.PI/2;c.position.set((Math.random()*2-1)*4,0.5,-30-Math.random()*10);c.userData={type:'coin'};scene.add(c);coinObjects.push(c)}

// HUD update function
function updateHUD(){if(gameState!=='play')return;$('scoreText').textContent=score;$('comboCount').textContent=combo;if(combo>1){$('comboWrap').classList.remove('hidden');$('comboWrap').style.animation='none';$('comboWrap').offsetHeight;$('comboWrap').style.animation='pulse .2s ease-out'}else{$('comboWrap').classList.add('hidden')}if(shieldActive){$('shieldIndicator').classList.remove('hidden')}else{$('shieldIndicator').classList.add('hidden')}if(slowMoActive){$('slowmoIndicator').classList.remove('hidden')}else{$('slowmoIndicator').classList.add('hidden')}if(rapidFireActive){$('rapidFireIndicator').classList.remove('hidden')}else{$('rapidFireIndicator').classList.add('hidden')}if(magnetActive){$('magnetIndicator').classList.remove('hidden')}else{$('magnetIndicator').classList.add('hidden')}if(freezeActive){$('freezeIndicator').classList.remove('hidden')}else{$('freezeIndicator').classList.add('hidden')}}
})();
